services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:8000"
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "3000:3000"
    command: >
      sh -c "npm start"